certamen/src/Entity/BandasDeMusica.php
<?php

namespace App\Entity;

use App\Repository\BandasDeMusicaRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BandasDeMusicaRepository::class)
 */
class BandasDeMusica
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero_de_musicos;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_director;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pueblo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $provincia;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $codigo_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telefono;



    /**
     * @ORM\ManyToOne(targetEntity=Certamenes::class, inversedBy="bandas")
     */
    private $certamenes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $correo_electronico;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="bandasDeMusica", cascade={"persist", "remove"})
     */
    private $usuario;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getNumeroDeMusicos(): ?int
    {
        return $this->numero_de_musicos;
    }

    public function setNumeroDeMusicos(int $numero_de_musicos): self
    {
        $this->numero_de_musicos = $numero_de_musicos;

        return $this;
    }

    public function getNombreDirector(): ?string
    {
        return $this->nombre_director;
    }

    public function setNombreDirector(string $nombre_director): self
    {
        $this->nombre_director = $nombre_director;

        return $this;
    }

    public function getPueblo(): ?string
    {
        return $this->pueblo;
    }

    public function setPueblo(string $pueblo): self
    {
        $this->pueblo = $pueblo;

        return $this;
    }

    public function getProvincia(): ?string
    {
        return $this->provincia;
    }

    public function setProvincia(string $provincia): self
    {
        $this->provincia = $provincia;

        return $this;
    }

    public function getCodigoPostal(): ?string
    {
        return $this->codigo_postal;
    }

    public function setCodigoPostal(string $codigo_postal): self
    {
        $this->codigo_postal = $codigo_postal;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }


    public function getCertamenes(): ?Certamenes
    {
        return $this->certamenes;
    }

    public function setCertamenes(?Certamenes $certamenes): self
    {
        $this->certamenes = $certamenes;

        return $this;
    }

    public function getCorreoElectronico(): ?string
    {
        return $this->correo_electronico;
    }

    public function setCorreoElectronico(string $correo_electronico): self
    {
        $this->correo_electronico = $correo_electronico;

        return $this;
    }

    public function getUsuario(): ?User
    {
        return $this->usuario;
    }

    public function setUsuario(?User $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

}

certamen/src/Form/BandasDeMusicaType.php
<?php

namespace App\Form;

use App\Entity\BandasDeMusica;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BandasDeMusicaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
            ->add('numero_de_musicos')
            ->add('nombre_director')
            ->add('pueblo')
            ->add('provincia')
            ->add('codigo_postal')
            ->add('telefono')
            ->add('correo_electronico')
            ->add('certamenes')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => BandasDeMusica::class,
        ]);
    }
}

certamen/src/Controller/BandasDeMusicaController.php
<?php

namespace App\Controller;

use App\Entity\BandasDeMusica;
use App\Form\BandasDeMusicaType;
use App\Repository\BandasDeMusicaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/bandasdemusica")
 */
class BandasDeMusicaController extends AbstractController
{
    /**
     * @Route("/", name="app_bandas_de_musica_index", methods={"GET"})
     */
    public function index(BandasDeMusicaRepository $bandasDeMusicaRepository): Response
    {
        return $this->render('bandas_de_musica/index.html.twig', [
            'bandas_de_musicas' => $bandasDeMusicaRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_bandas_de_musica_new", methods={"GET", "POST"})
     */
    public function new(Request $request, BandasDeMusicaRepository $bandasDeMusicaRepository): Response
    {
        $bandasDeMusica = new BandasDeMusica();
        $form = $this->createForm(BandasDeMusicaType::class, $bandasDeMusica);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bandasDeMusicaRepository->add($bandasDeMusica, true);

            return $this->redirectToRoute('app_bandas_de_musica_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('bandas_de_musica/new.html.twig', [
            'bandas_de_musica' => $bandasDeMusica,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_bandas_de_musica_show", methods={"GET"})
     */
    public function show(BandasDeMusica $bandasDeMusica): Response
    {
        return $this->render('bandas_de_musica/show.html.twig', [
            'bandas_de_musica' => $bandasDeMusica,
        ]);
    }


    /**
     * @Route("/{id}/edit", name="app_bandas_de_musica_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, BandasDeMusica $bandasDeMusica, BandasDeMusicaRepository $bandasDeMusicaRepository): Response
    {
        $form = $this->createForm(BandasDeMusicaType::class, $bandasDeMusica);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bandasDeMusicaRepository->add($bandasDeMusica, true);

            return $this->redirectToRoute('app_bandas_de_musica_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('bandas_de_musica/edit.html.twig', [
            'bandas_de_musica' => $bandasDeMusica,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_bandas_de_musica_delete", methods={"POST"})
     */
    public function delete(Request $request, BandasDeMusica $bandasDeMusica, BandasDeMusicaRepository $bandasDeMusicaRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$bandasDeMusica->getId(), $request->request->get('_token'))) {
            $bandasDeMusicaRepository->remove($bandasDeMusica, true);
        }

        return $this->redirectToRoute('app_bandas_de_musica_index', [], Response::HTTP_SEE_OTHER);
    }
}

certamen/templates/bandas_de_musica/_delete_form.html.twig
<form method="post"
  action="{{
  path(
    'app_bandas_de_musica_delete',
    {
      id: bandas_de_musica.id
    }
  )
  }}"
  onsubmit="return confirm('¿Seguro que quieres borrar esta banda?');">
  <input type="hidden"
    name="_token"
    class="form-control"
    value="{{ csrf_token('delete' ~ bandas_de_musica.id) }}" />
  <div class="container">
    <div class="vertical-center">
      <button class="btn btn-danger">Borrar</button>
    </div>
  </div>
</form>

certamen/templates/bandas_de_musica/_form.html.twig
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{{ form_start(form) }}
{{ form_widget(form) }}
<div class="container">
  <div class="vertical-center">
    <button class="btn btn-primary">{{ button_label|default('Crear') }}</button>
  </div>
</div> 
{{ form_end(form) }}

certamen/templates/bandas_de_musica/edit.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{% block title %}Edit BandasDeMusica{% endblock %}

{% block body %}
  <h1 style="text-align:center">
    Editar banda de música
  </h1>
  <div class="mb-3" style="width: 300px;
  margin: auto;">
    <div class="col-auto">
      {{
        include(
          'bandas_de_musica/_form.html.twig',
          {
            button_label: 'Guardar'
          }
        )
      }}
    </div>
  </div>
  <div class="container">
    <div class="vertical-center">
      <a class="btn btn-info" href="{{ path('app_bandas_de_musica_index') }}">
        Volver a la lista
      </a>
    </div>
  </div>
  {{ include('bandas_de_musica/_delete_form.html.twig') }}
{% endblock %}

certamen/templates/bandas_de_musica/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  BandasDeMusica index
{% endblock %}

{% block body %}
  <h1 style="text-align:center">
    Bandas de Música
  </h1>

  <table class="table table-bordered border-primary" style="text-align:center">
    <thead>
      <tr>
        <th>
          Nombre
        </th>
        <th>
          Número de músicos
        </th>
        <th>
          Nombre del director
        </th>
        <th>
          Municipio
        </th>
        <th>
          Provincia
        </th>
        <th>
          Código postal
        </th>
        <th>
          Teléfono
        </th>
        {# <th>Ganador de:</th> #}
        {% if is_granted('ROLE_ADMIN') %}>
        <th>
          Opciones
        </th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for bandas_de_musica in bandas_de_musicas %}
        <tr>
          <td>
            {{ bandas_de_musica.nombre }}
          </td>
          <td>
            {{ bandas_de_musica.numeroDeMusicos }}
          </td>
          <td>
            {{ bandas_de_musica.nombreDirector }}
          </td>
          <td>
            {{ bandas_de_musica.pueblo }}
          </td>
          <td>
            {{ bandas_de_musica.provincia }}
          </td>
          <td>
            {{ bandas_de_musica.codigoPostal }}
          </td>
          <td>
            {{ bandas_de_musica.telefono }}
          </td>
          {# <td>{{ bandas_de_musica.certamenes }}</td> #}
          <td>
            {% if is_granted('ROLE_ADMIN') %}
              <a class="btn btn-secondary"
                href="{{
                path(
                  'app_bandas_de_musica_show',
                  {
                    id: bandas_de_musica.id
                  }
                )
                }}">
                Mostrar
              </a>
            {% endif %}
            {% if
              is_granted('ROLE_ADMIN')
                or (is_granted('ROLE_USER')
                  and bandas_de_musica.getUsuario()) %}
              <a class="btn btn-warning"
                href="{{
                path(
                  'app_bandas_de_musica_edit',
                  {
                    id: bandas_de_musica.id
                  }
                )
                }}">
                Editar
              </a>
            {% endif %}
            {% if
              is_granted('ROLE_ADMIN')
                or (is_granted('ROLE_USER')
                  and bandas_de_musica.getUsuario()) %}
              <a class="btn btn-danger"
                href="{{
                path(
                  'app_bandas_de_musica_delete',
                  {
                    id: bandas_de_musica.id
                  }
                )
                }}">
                Borrar
              </a>
            {% endif %}
          </td>
        </tr>
      {% else %}
        <tr>
          <td colspan="10">
            No se han encontrado resultados
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {# <div class="container">
    <div class="vertical-center">
      <a class="btn btn-success" href="{{ path('app_bandas_de_musica_new') }}">
        Crear banda nueva
      </a>
    </div>
  </div> #}
{% endblock %}

certamen/templates/bandas_de_musica/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  New BandasDeMusica
{% endblock %}

{% block body %}
  <h1 style="text-align:center">
    Crear banda nueva
  </h1>

  <div class="mb-3" style="width: 300px;  margin: auto;">
    <div class="col-auto">
      {{ include('bandas_de_musica/_form.html.twig') }}
    </div>
  </div>

  <div class="container">
    <div class="vertical-center">
      <a class="btn btn-info" href="{{ path('app_bandas_de_musica_index') }}">
        Volver a la lista
      </a>
    </div>
  </div>
{% endblock %}

certamen/templates/bandas_de_musica/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}BandasDeMusica{% endblock %}

{% block body %}
    <h1 style="text-align:center">Banda de música</h1>

    <div class="mb-3" style="width: 300px; margin: auto;">
        <div class="container">
            <table class="table table-bordered border-primary">
                <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ bandas_de_musica.id }}</td>
                    </tr>
                    <tr>
                        <th>Nombre</th>
                        <td>{{ bandas_de_musica.nombre }}</td>
                    </tr>
                    <tr>
                        <th>Número de músicos</th>
                        <td>{{ bandas_de_musica.numeroDeMusicos }}</td>
                    </tr>
                    <tr>
                        <th>Nombre del director</th>
                        <td>{{ bandas_de_musica.nombreDirector }}</td>
                    </tr>
                    <tr>
                        <th>Municipio</th>
                        <td>{{ bandas_de_musica.pueblo }}</td>
                    </tr>
                    <tr>
                        <th>Provincia</th>
                        <td>{{ bandas_de_musica.provincia }}</td>
                    </tr>
                    <tr>
                        <th>Código postal</th>
                        <td>{{ bandas_de_musica.codigoPostal }}</td>
                    </tr>
                    <tr>
                        <th>Teléfono</th>
                        <td>{{ bandas_de_musica.telefono }}</td>
                    </tr>
                    <tr>
                        <th>Correo electrónico</th>
                        <td>{{ bandas_de_musica.correoElectronico }}</td>
                    </tr>
                    <tr>
                        <th>Matriculado en:</th>
                        <td>{{ bandas_de_musica.certamenes }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="container">
            <a class="btn btn-info" href="{{ path('app_bandas_de_musica_index') }}">Volver a la lista</a>
            <a class="btn btn-warning" href="{{ path('app_bandas_de_musica_edit', {'id': bandas_de_musica.id}) }}">Editar</a>
    </div>
    {{ include('bandas_de_musica/_delete_form.html.twig') }}
{% endblock %}